hackIT/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('watch/', include('toire.urls')),
    re_path(r'^convert/', include('lazysignup.urls')),
]

toire/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'toire'
urlpatterns = [
    path('', views.index, name='index'),
    # re_path(r'^convert/', include('lazysignup.urls')),
    path('ex', views.export_logs, name='export_logs'),
    path('allLogs/', views.allLogs, name="allLogs"),
    path('guest/', views.guest_test, name="guest"),
]

toire/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Record(models.Model):
    note = models.CharField(max_length = 1000)
    date = models.DateField()
    time = models.DateTimeField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    is_anonymous = models.BooleanField(default=False)

    def __str__(self):
    	return self.note

    def as_json(self):
        return dict(
            note=self.note, 
            time=self.time.isoformat(),
            )

toire/forms.py
from django import forms

class NoteForm(forms.Form):
    log_notes = forms.CharField(label='Notes', max_length=200)

toire/views.py
from lazysignup.decorators import allow_lazy_user

from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from .resources import RecordResource
from datetime import datetime
from .models import Record

from .forms import NoteForm

from lazysignup.templatetags.lazysignup_tags import is_lazy_user

# Create your views here.
@allow_lazy_user
def index(request):
    if request.method == 'POST':
        r = Record(note = request.POST.get('notes'), date = datetime.today(), time = datetime.now(), user_id = request.user, is_anonymous=is_lazy_user(request.user))

        r.save()
    r = Record.objects.filter(user_id = request.user).order_by('-id')[0]
    ar = Record.objects.filter(user_id = request.user).order_by('-id')
    return render(request, 'toire/index.html', context = {'records':r, 'arecods':ar})

@allow_lazy_user
def export_logs(request):
    context = {

    }
    record_resource = RecordResource()
    queryset = Record.objects.filter(user_id = request.user)
    dataset = record_resource.export(queryset)
    response = HttpResponse(dataset.json, content_type='application/json')
    response['Content-Disposition'] = 'attachment; filename="records.json"'
    return response

@allow_lazy_user
def allLogs(request):
    context = {

    }
    return render(request, 'toire/allLogs.html', context)

@allow_lazy_user
def guest_test(request):
    # attrs = {}
    # for k, v in request.user:
    #     attrs[k] = v

    context = {
        'username' : request.user.username,
        'user_id' : request.user.id,
        'is_lazy' : is_lazy_user(request.user)
        # 'attrs': attrs
    }
    
    return render(request, 'toire/dummy_index.html', context)

toire/templates/toire/allLogs.html
<!DOCTYPE html>
<html>
<head>
    <title>Toire</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'toire/jscss/bootstrap-4.0.0/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'toire/jscss/font-awesome-4.7.0/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'toire/jscss/DataTables/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'toire/jscss/site.css' %}">
</head>
<body>
    <div id="wrapper">
        <div class="container tbl-custom">
            <h1 class="al-title">
                <a href="http://127.0.0.1:8000/watch"><span title="Back" class="fa fa-caret-left"></span></a> &nbsp;All Logs
            </h1>
            <table id="tblLogs" class="display">
                <thead>
                <tr>
                    <th>Time logged</th>
                    <th>Notes</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</body>


<script type="text/javascript" src="{% static 'toire/jscss/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'toire/jscss/bootstrap-4.0.0/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'toire/jscss/DataTables/datatables.js' %}"></script>
<script type="text/javascript" src="{% static 'toire/jscss/site.js' %}"></script>
</html>

toire/templates/toire/dummy_index.html
<strong>User:</strong> {{ username }}
<br/ >
<strong>  ID:</strong> {{ user_id }}
<br/ >
<strong>Lazy?</strong> {{ is_lazy }}

{% comment %}
<ul>
	{% for k, v in attrs %}
		<li> {{k}} : {{v}} </li>
	{% endfor %}
</ul>
{% endcomment %}

toire/templates/toire/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Toire</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static '/toire/jscss/bootstrap-4.0.0/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/toire/jscss/font-awesome-4.7.0/css/font-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/toire/jscss/site.css' %}">
</head>
<body>
<div id="wrapper">
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="#menu-toggle2" id="menu-toggle2">
                    <span class="fa fa-bars"></span> Recent Logs
                </a>
            </li>
            {% for b in arecords %}
            <li>
                {{ b.time }}|{{ b.note }}
            </li>
            {% endfor %}
        </ul>
    </div>
    <div id="page-content-wrapper">
        <a href="#menu-toggle" class="logs" id="menu-toggle"><span class="fa fa-bars"></span> Logs</a>
        <div class="container">
            <div class="clockcontainer">
                <div class="clock">
                    <ul>
                        <li id="hours">10</li>
                        <li id="point">:</li>
                        <li id="min">13</li>
                    </ul>
                    <div id="Date">Monday 14 January 2013</div>
                    <hr />
                    <form action="{% url 'toire:index' %}" method="post">
                        {% csrf_token %}
                        <textarea id="notes" class="form-control note" placeholder="Your notes here..." name="notes"></textarea>
                        <input type="submit" class="btn btn-success btn-lg log" value="LOG"/>
                    </form>
                </div>
            </div>
         </div>
         {% if records %}
        <div class="container">
            <div class="prevlogcontainer">
                <div class="prevlog">
                    <p class="plog-label">Previous Log</p>
                    <div class="plog-left">
                        <span class="prev-log-time">{{ records.time }}<br/></span>
                    </div>
                    <div class="plog-right">
                        {{ records.note }}
                    </div>
                    <a href="http://127.0.0.1:8000/watch/allLogs/" class="viewlogs">View all</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    </div>

</body>
</html>

<script type="text/javascript" src="{% static 'toire/jscss/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'toire/jscss/bootstrap-4.0.0/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'toire/jscss/DataTables/datatables.js' %}"></script>
<script type="text/javascript" src="{% static 'toire/jscss/site.js' %}"></script>